//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.22 at 10:36:41 PM EDT 
//


package com.reqo.ironhold.reader.bloomberg.model.dscl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisclaimerType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="DisclaimerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DisclaimerReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DisclaimerText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisclaimerType", propOrder = {
        "disclaimerReference",
        "disclaimerText"
})
public class DisclaimerType {

    @XmlElement(name = "DisclaimerReference", required = true)
    protected String disclaimerReference;
    @XmlElement(name = "DisclaimerText", required = true)
    protected String disclaimerText;

    /**
     * Gets the value of the disclaimerReference property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDisclaimerReference() {
        return disclaimerReference;
    }

    /**
     * Sets the value of the disclaimerReference property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDisclaimerReference(String value) {
        this.disclaimerReference = value;
    }

    /**
     * Gets the value of the disclaimerText property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDisclaimerText() {
        return disclaimerText;
    }

    /**
     * Sets the value of the disclaimerText property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDisclaimerText(String value) {
        this.disclaimerText = value;
    }

}
