//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 07:23:03 PM EDT 
//


package com.reqo.ironhold.reader.bloomberg.model.ib;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.reqo.ironhold.reader.bloomberg.model.ib package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.reqo.ironhold.reader.bloomberg.model.ib
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link LoginName }
     */
    public LoginName createLoginName() {
        return new LoginName();
    }

    /**
     * Create an instance of {@link FirstName }
     */
    public FirstName createFirstName() {
        return new FirstName();
    }

    /**
     * Create an instance of {@link LastName }
     */
    public LastName createLastName() {
        return new LastName();
    }

    /**
     * Create an instance of {@link ClientID1 }
     */
    public ClientID1 createClientID1() {
        return new ClientID1();
    }

    /**
     * Create an instance of {@link ClientID2 }
     */
    public ClientID2 createClientID2() {
        return new ClientID2();
    }

    /**
     * Create an instance of {@link UUID }
     */
    public UUID createUUID() {
        return new UUID();
    }

    /**
     * Create an instance of {@link FirmNumber }
     */
    public FirmNumber createFirmNumber() {
        return new FirmNumber();
    }

    /**
     * Create an instance of {@link AccountNumber }
     */
    public AccountNumber createAccountNumber() {
        return new AccountNumber();
    }

    /**
     * Create an instance of {@link CompanyName }
     */
    public CompanyName createCompanyName() {
        return new CompanyName();
    }

    /**
     * Create an instance of {@link EmailAddress }
     */
    public EmailAddress createEmailAddress() {
        return new EmailAddress();
    }

    /**
     * Create an instance of {@link CorporateEmailAddress }
     */
    public CorporateEmailAddress createCorporateEmailAddress() {
        return new CorporateEmailAddress();
    }

    /**
     * Create an instance of {@link Attachment }
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link DateTime }
     */
    public DateTime createDateTime() {
        return new DateTime();
    }

    /**
     * Create an instance of {@link DateTimeUTC }
     */
    public DateTimeUTC createDateTimeUTC() {
        return new DateTimeUTC();
    }

    /**
     * Create an instance of {@link ConversationID }
     */
    public ConversationID createConversationID() {
        return new ConversationID();
    }

    /**
     * Create an instance of {@link FileName }
     */
    public FileName createFileName() {
        return new FileName();
    }

    /**
     * Create an instance of {@link Reference }
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link FileID }
     */
    public FileID createFileID() {
        return new FileID();
    }

    /**
     * Create an instance of {@link FileSize }
     */
    public FileSize createFileSize() {
        return new FileSize();
    }

    /**
     * Create an instance of {@link NextFile }
     */
    public NextFile createNextFile() {
        return new NextFile();
    }

    /**
     * Create an instance of {@link Inviter }
     */
    public Inviter createInviter() {
        return new Inviter();
    }

    /**
     * Create an instance of {@link History }
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link StartTime }
     */
    public StartTime createStartTime() {
        return new StartTime();
    }

    /**
     * Create an instance of {@link StartTimeUTC }
     */
    public StartTimeUTC createStartTimeUTC() {
        return new StartTimeUTC();
    }

    /**
     * Create an instance of {@link EndTime }
     */
    public EndTime createEndTime() {
        return new EndTime();
    }

    /**
     * Create an instance of {@link EndTimeUTC }
     */
    public EndTimeUTC createEndTimeUTC() {
        return new EndTimeUTC();
    }

    /**
     * Create an instance of {@link Version }
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link Content }
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link SystemMessage }
     */
    public SystemMessage createSystemMessage() {
        return new SystemMessage();
    }

    /**
     * Create an instance of {@link Conversation }
     */
    public Conversation createConversation() {
        return new Conversation();
    }

    /**
     * Create an instance of {@link RoomID }
     */
    public RoomID createRoomID() {
        return new RoomID();
    }

    /**
     * Create an instance of {@link Invite }
     */
    public Invite createInvite() {
        return new Invite();
    }

    /**
     * Create an instance of {@link Invitee }
     */
    public Invitee createInvitee() {
        return new Invitee();
    }

    /**
     * Create an instance of {@link ParticipantEntered }
     */
    public ParticipantEntered createParticipantEntered() {
        return new ParticipantEntered();
    }

    /**
     * Create an instance of {@link ParticipantLeft }
     */
    public ParticipantLeft createParticipantLeft() {
        return new ParticipantLeft();
    }

    /**
     * Create an instance of {@link Message }
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link FileDump }
     */
    public FileDump createFileDump() {
        return new FileDump();
    }

}
