var matched,browser;jQuery.uaMatch=function(a){a=a.toLowerCase();a=/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}};matched=jQuery.uaMatch(navigator.userAgent);browser={};matched.browser&&(browser[matched.browser]=!0,browser.version=matched.version);
browser.chrome?browser.webkit=!0:browser.webkit&&(browser.safari=!0);jQuery.browser=browser;jQuery.cookie=function(a,c,e){if("undefined"!=typeof c){e=e||{};null===c&&(c="",e.expires=-1);var b="";e.expires&&("number"==typeof e.expires||e.expires.toUTCString)&&("number"==typeof e.expires?(b=new Date,b.setTime(b.getTime()+864E5*e.expires)):b=e.expires,b="; expires="+b.toUTCString());var d=e.path?"; path="+e.path:"",f=e.domain?"; domain="+e.domain:"";e=e.secure?"; secure":"";document.cookie=[a,"=",encodeURIComponent(c),b,d,f,e].join("")}else{c=null;if(document.cookie&&""!=document.cookie)for(e=
document.cookie.split(";"),b=0;b<e.length;b++)if(d=jQuery.trim(e[b]),d.substring(0,a.length+1)==a+"="){c=decodeURIComponent(d.substring(a.length+1));break}return c}};if(!jQuery)throw Error("Bootstrap requires jQuery");
+function(a){a.fn.emulateTransitionEnd=function(c){var e=!1,b=this;a(this).one(a.support.transition.end,function(){e=!0});return setTimeout(function(){e||a(b).trigger(a.support.transition.end)},c),this};a(function(){var c=a.support,e;a:{e=document.createElement("bootstrap");var b={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},d;for(d in b)if(void 0!==e.style[d]){e={end:b[d]};break a}e=void 0}c.transition=
e})}(window.jQuery);
+function(a){var c=function(b){a(b).on("click",'[data-dismiss="alert"]',this.close)};c.prototype.close=function(b){function d(){e.trigger("closed.bs.alert").remove()}var f=a(this),c=f.attr("data-target");c||(c=f.attr("href"),c=c&&c.replace(/.*(?=#[^\s]*$)/,""));var e=a(c);b&&b.preventDefault();e.length||(e=f.hasClass("alert")?f:f.parent());e.trigger(b=a.Event("close.bs.alert"));b.isDefaultPrevented()||(e.removeClass("in"),a.support.transition&&e.hasClass("fade")?e.one(a.support.transition.end,d).emulateTransitionEnd(150):
d())};var e=a.fn.alert;a.fn.alert=function(b){return this.each(function(){var d=a(this),f=d.data("bs.alert");f||d.data("bs.alert",f=new c(this));"string"==typeof b&&f[b].call(d)})};a.fn.alert.Constructor=c;a.fn.alert.noConflict=function(){return a.fn.alert=e,this};a(document).on("click.bs.alert.data-api",'[data-dismiss="alert"]',c.prototype.close)}(window.jQuery);
+function(a){var c=function(b,d){this.$element=a(b);this.options=a.extend({},c.DEFAULTS,d)};c.DEFAULTS={loadingText:"loading..."};c.prototype.setState=function(a){var d=this.$element,f=d.is("input")?"val":"html",c=d.data();a+="Text";c.resetText||d.data("resetText",d[f]());d[f](c[a]||this.options[a]);setTimeout(function(){"loadingText"==a?d.addClass("disabled").attr("disabled","disabled"):d.removeClass("disabled").removeAttr("disabled")},0)};c.prototype.toggle=function(){var a=this.$element.closest('[data-toggle="buttons"]');
a.length&&"radio"===this.$element.find("input").prop("checked",!this.$element.hasClass("active")).trigger("change").prop("type")&&a.find(".active").removeClass("active");this.$element.toggleClass("active")};var e=a.fn.button;a.fn.button=function(b){return this.each(function(){var d=a(this),f=d.data("bs.button"),e="object"==typeof b&&b;f||d.data("bs.button",f=new c(this,e));"toggle"==b?f.toggle():b&&f.setState(b)})};a.fn.button.Constructor=c;a.fn.button.noConflict=function(){return a.fn.button=e,this};
a(document).on("click.bs.button.data-api","[data-toggle^=button]",function(b){var d=a(b.target);d.hasClass("btn")||(d=d.closest(".btn"));d.button("toggle");b.preventDefault()})}(window.jQuery);
+function(a){var c=function(b,d){this.$element=a(b);this.$indicators=this.$element.find(".carousel-indicators");this.options=d;this.paused=this.sliding=this.interval=this.$active=this.$items=null;"hover"==this.options.pause&&this.$element.on("mouseenter",a.proxy(this.pause,this)).on("mouseleave",a.proxy(this.cycle,this))};c.DEFAULTS={interval:5E3,pause:"hover",wrap:!0};c.prototype.cycle=function(b){return b||(this.paused=!1),this.interval&&clearInterval(this.interval),this.options.interval&&!this.paused&&
(this.interval=setInterval(a.proxy(this.next,this),this.options.interval)),this};c.prototype.getActiveIndex=function(){return this.$active=this.$element.find(".item.active"),this.$items=this.$active.parent().children(),this.$items.index(this.$active)};c.prototype.to=function(b){var d=this,f=this.getActiveIndex();return b>this.$items.length-1||0>b?void 0:this.sliding?this.$element.one("slid",function(){d.to(b)}):f==b?this.pause().cycle():this.slide(b>f?"next":"prev",a(this.$items[b]))};c.prototype.pause=
function(b){return b||(this.paused=!0),this.$element.find(".next, .prev").length&&a.support.transition.end&&(this.$element.trigger(a.support.transition.end),this.cycle(!0)),this.interval=clearInterval(this.interval),this};c.prototype.next=function(){return this.sliding?void 0:this.slide("next")};c.prototype.prev=function(){return this.sliding?void 0:this.slide("prev")};c.prototype.slide=function(b,d){var f=this.$element.find(".item.active"),c=d||f[b](),e=this.interval,l="next"==b?"left":"right",n=
"next"==b?"first":"last",t=this;if(!c.length){if(!this.options.wrap)return;c=this.$element.find(".item")[n]()}this.sliding=!0;e&&this.pause();n=a.Event("slide.bs.carousel",{relatedTarget:c[0],direction:l});if(!c.hasClass("active")){if(this.$indicators.length&&(this.$indicators.find(".active").removeClass("active"),this.$element.one("slid",function(){var b=a(t.$indicators.children()[t.getActiveIndex()]);b&&b.addClass("active")})),a.support.transition&&this.$element.hasClass("slide")){if(this.$element.trigger(n),
n.isDefaultPrevented())return;c.addClass(b);c[0].offsetWidth;f.addClass(l);c.addClass(l);f.one(a.support.transition.end,function(){c.removeClass([b,l].join(" ")).addClass("active");f.removeClass(["active",l].join(" "));t.sliding=!1;setTimeout(function(){t.$element.trigger("slid")},0)}).emulateTransitionEnd(600)}else{if(this.$element.trigger(n),n.isDefaultPrevented())return;f.removeClass("active");c.addClass("active");this.sliding=!1;this.$element.trigger("slid")}return e&&this.cycle(),this}};var e=
a.fn.carousel;a.fn.carousel=function(b){return this.each(function(){var d=a(this),f=d.data("bs.carousel"),e=a.extend({},c.DEFAULTS,d.data(),"object"==typeof b&&b),p="string"==typeof b?b:e.slide;f||d.data("bs.carousel",f=new c(this,e));"number"==typeof b?f.to(b):p?f[p]():e.interval&&f.pause().cycle()})};a.fn.carousel.Constructor=c;a.fn.carousel.noConflict=function(){return a.fn.carousel=e,this};a(document).on("click.bs.carousel.data-api","[data-slide], [data-slide-to]",function(b){var d,f=a(this),
c=a(f.attr("data-target")||(d=f.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,""));d=a.extend({},c.data(),f.data());var e=f.attr("data-slide-to");e&&(d.interval=!1);c.carousel(d);(e=f.attr("data-slide-to"))&&c.data("bs.carousel").to(e);b.preventDefault()});a(window).on("load",function(){a('[data-ride="carousel"]').each(function(){var b=a(this);b.carousel(b.data())})})}(window.jQuery);
+function(a){var c=function(b,d){this.$element=a(b);this.options=a.extend({},c.DEFAULTS,d);this.transitioning=null;this.options.parent&&(this.$parent=a(this.options.parent));this.options.toggle&&this.toggle()};c.DEFAULTS={toggle:!0};c.prototype.dimension=function(){return this.$element.hasClass("width")?"width":"height"};c.prototype.show=function(){if(!this.transitioning&&!this.$element.hasClass("in")){var b=a.Event("show.bs.collapse");if(this.$element.trigger(b),!b.isDefaultPrevented()){if((b=this.$parent&&
this.$parent.find("> .panel > .in"))&&b.length){var d=b.data("bs.collapse");if(d&&d.transitioning)return;b.collapse("hide");d||b.data("bs.collapse",null)}var f=this.dimension();this.$element.removeClass("collapse").addClass("collapsing")[f](0);this.transitioning=1;b=function(){this.$element.removeClass("collapsing").addClass("in")[f]("auto");this.transitioning=0;this.$element.trigger("shown.bs.collapse")};if(!a.support.transition)return b.call(this);d=a.camelCase(["scroll",f].join("-"));this.$element.one(a.support.transition.end,
a.proxy(b,this)).emulateTransitionEnd(350)[f](this.$element[0][d])}}};c.prototype.hide=function(){if(!this.transitioning&&this.$element.hasClass("in")){var b=a.Event("hide.bs.collapse");if(this.$element.trigger(b),!b.isDefaultPrevented()){b=this.dimension();this.$element[b](this.$element[b]())[0].offsetHeight;this.$element.addClass("collapsing").removeClass("collapse").removeClass("in");this.transitioning=1;var d=function(){this.transitioning=0;this.$element.trigger("hidden.bs.collapse").removeClass("collapsing").addClass("collapse")};
return a.support.transition?(this.$element[b](0).one(a.support.transition.end,a.proxy(d,this)).emulateTransitionEnd(350),void 0):d.call(this)}}};c.prototype.toggle=function(){this[this.$element.hasClass("in")?"hide":"show"]()};var e=a.fn.collapse;a.fn.collapse=function(b){return this.each(function(){var d=a(this),f=d.data("bs.collapse"),e=a.extend({},c.DEFAULTS,d.data(),"object"==typeof b&&b);f||d.data("bs.collapse",f=new c(this,e));"string"==typeof b&&f[b]()})};a.fn.collapse.Constructor=c;a.fn.collapse.noConflict=
function(){return a.fn.collapse=e,this};a(document).on("click.bs.collapse.data-api","[data-toggle=collapse]",function(b){var d,f=a(this);b=f.attr("data-target")||b.preventDefault()||(d=f.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"");d=a(b);var c=(b=d.data("bs.collapse"))?"toggle":f.data(),e=f.attr("data-parent"),l=e&&a(e);b&&b.transitioning||(l&&l.find('[data-toggle=collapse][data-parent="'+e+'"]').not(f).addClass("collapsed"),f[d.hasClass("in")?"addClass":"removeClass"]("collapsed"));d.collapse(c)})}(window.jQuery);
+function(a){function c(){a(b).remove();a(d).each(function(b){var d=e(a(this));d.hasClass("open")&&(d.trigger(b=a.Event("hide.bs.dropdown")),b.isDefaultPrevented()||d.removeClass("open").trigger("hidden.bs.dropdown"))})}function e(b){var d=b.attr("data-target");d||(d=b.attr("href"),d=d&&/#/.test(d)&&d.replace(/.*(?=#[^\s]*$)/,""));return(d=d&&a(d))&&d.length?d:b.parent()}var b=".dropdown-backdrop",d="[data-toggle=dropdown]",f=function(b){a(b).on("click.bs.dropdown",this.toggle)};f.prototype.toggle=
function(b){var d=a(this);if(!d.is(".disabled, :disabled")){var f=e(d),x=f.hasClass("open");if(c(),!x){if("ontouchstart"in document.documentElement&&!f.closest(".navbar-nav").length&&a('<div class="dropdown-backdrop"/>').insertAfter(a(this)).on("click",c),f.trigger(b=a.Event("show.bs.dropdown")),b.isDefaultPrevented())return;f.toggleClass("open").trigger("shown.bs.dropdown");d.focus()}return!1}};f.prototype.keydown=function(b){if(/(38|40|27)/.test(b.keyCode)){var f=a(this);if(b.preventDefault(),b.stopPropagation(),
!f.is(".disabled, :disabled")){var c=e(f),x=c.hasClass("open");if(!x||x&&27==b.keyCode)return 27==b.which&&c.find(d).focus(),f.click();f=a("[role=menu] li:not(.divider):visible a",c);f.length&&(c=f.index(f.filter(":focus")),38==b.keyCode&&0<c&&c--,40==b.keyCode&&c<f.length-1&&c++,~c||(c=0),f.eq(c).focus())}}};var x=a.fn.dropdown;a.fn.dropdown=function(b){return this.each(function(){var d=a(this),c=d.data("dropdown");c||d.data("dropdown",c=new f(this));"string"==typeof b&&c[b].call(d)})};a.fn.dropdown.Constructor=
f;a.fn.dropdown.noConflict=function(){return a.fn.dropdown=x,this};a(document).on("click.bs.dropdown.data-api",c).on("click.bs.dropdown.data-api",".dropdown form",function(b){b.stopPropagation()}).on("click.bs.dropdown.data-api",d,f.prototype.toggle).on("keydown.bs.dropdown.data-api",d+", [role=menu]",f.prototype.keydown)}(window.jQuery);
+function(a){var c=function(b,d){this.options=d;this.$element=a(b);this.$backdrop=this.isShown=null;this.options.remote&&this.$element.load(this.options.remote)};c.DEFAULTS={backdrop:!0,keyboard:!0,show:!0};c.prototype.toggle=function(b){return this[this.isShown?"hide":"show"](b)};c.prototype.show=function(b){var d=this,f=a.Event("show.bs.modal",{relatedTarget:b});this.$element.trigger(f);this.isShown||f.isDefaultPrevented()||(this.isShown=!0,this.escape(),this.$element.on("click.dismiss.modal",'[data-dismiss="modal"]',
a.proxy(this.hide,this)),this.backdrop(function(){var f=a.support.transition&&d.$element.hasClass("fade");d.$element.parent().length||d.$element.appendTo(document.body);d.$element.show();f&&d.$element[0].offsetWidth;d.$element.addClass("in").attr("aria-hidden",!1);d.enforceFocus();var c=a.Event("shown.bs.modal",{relatedTarget:b});f?d.$element.find(".modal-dialog").one(a.support.transition.end,function(){d.$element.focus().trigger(c)}).emulateTransitionEnd(300):d.$element.focus().trigger(c)}))};c.prototype.hide=
function(b){b&&b.preventDefault();b=a.Event("hide.bs.modal");this.$element.trigger(b);this.isShown&&!b.isDefaultPrevented()&&(this.isShown=!1,this.escape(),a(document).off("focusin.bs.modal"),this.$element.removeClass("in").attr("aria-hidden",!0).off("click.dismiss.modal"),a.support.transition&&this.$element.hasClass("fade")?this.$element.one(a.support.transition.end,a.proxy(this.hideModal,this)).emulateTransitionEnd(300):this.hideModal())};c.prototype.enforceFocus=function(){a(document).off("focusin.bs.modal").on("focusin.bs.modal",
a.proxy(function(b){this.$element[0]===b.target||this.$element.has(b.target).length||this.$element.focus()},this))};c.prototype.escape=function(){this.isShown&&this.options.keyboard?this.$element.on("keyup.dismiss.bs.modal",a.proxy(function(b){27==b.which&&this.hide()},this)):this.isShown||this.$element.off("keyup.dismiss.bs.modal")};c.prototype.hideModal=function(){var b=this;this.$element.hide();this.backdrop(function(){b.removeBackdrop();b.$element.trigger("hidden.bs.modal")})};c.prototype.removeBackdrop=
function(){this.$backdrop&&this.$backdrop.remove();this.$backdrop=null};c.prototype.backdrop=function(b){var d=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var f=a.support.transition&&d;if(this.$backdrop=a('<div class="modal-backdrop '+d+'" />').appendTo(document.body),this.$element.on("click.dismiss.modal",a.proxy(function(b){b.target===b.currentTarget&&("static"==this.options.backdrop?this.$element[0].focus.call(this.$element[0]):this.hide.call(this))},this)),
f&&this.$backdrop[0].offsetWidth,this.$backdrop.addClass("in"),b)f?this.$backdrop.one(a.support.transition.end,b).emulateTransitionEnd(150):b()}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),a.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(a.support.transition.end,b).emulateTransitionEnd(150):b()):b&&b()};var e=a.fn.modal;a.fn.modal=function(b,d){return this.each(function(){var f=a(this),e=f.data("bs.modal"),p=a.extend({},c.DEFAULTS,f.data(),"object"==typeof b&&
b);e||f.data("bs.modal",e=new c(this,p));"string"==typeof b?e[b](d):p.show&&e.show(d)})};a.fn.modal.Constructor=c;a.fn.modal.noConflict=function(){return a.fn.modal=e,this};a(document).on("click.bs.modal.data-api",'[data-toggle="modal"]',function(b){var d=a(this),f=d.attr("href"),c=a(d.attr("data-target")||f&&f.replace(/.*(?=#[^\s]+$)/,"")),f=c.data("modal")?"toggle":a.extend({remote:!/#/.test(f)&&f},c.data(),d.data());b.preventDefault();c.modal(f,this).one("hide",function(){d.is(":visible")&&d.focus()})});
a(document).on("show.bs.modal",".modal",function(){a(document.body).addClass("modal-open")}).on("hidden.bs.modal",".modal",function(){a(document.body).removeClass("modal-open")})}(window.jQuery);
+function(a){var c=function(b,a){this.type=this.options=this.enabled=this.timeout=this.hoverState=this.$element=null;this.init("tooltip",b,a)};c.DEFAULTS={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",title:"",delay:0,html:!1,container:!1};c.prototype.init=function(b,d,f){this.enabled=!0;this.type=b;this.$element=a(d);this.options=this.getOptions(f);b=this.options.trigger.split(" ");
for(d=b.length;d--;)if(f=b[d],"click"==f)this.$element.on("click."+this.type,this.options.selector,a.proxy(this.toggle,this));else if("manual"!=f){var c="hover"==f?"mouseleave":"blur";this.$element.on(("hover"==f?"mouseenter":"focus")+"."+this.type,this.options.selector,a.proxy(this.enter,this));this.$element.on(c+"."+this.type,this.options.selector,a.proxy(this.leave,this))}this.options.selector?this._options=a.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};c.prototype.getDefaults=
function(){return c.DEFAULTS};c.prototype.getOptions=function(b){return b=a.extend({},this.getDefaults(),this.$element.data(),b),b.delay&&"number"==typeof b.delay&&(b.delay={show:b.delay,hide:b.delay}),b};c.prototype.getDelegateOptions=function(){var b={},d=this.getDefaults();return this._options&&a.each(this._options,function(a,c){d[a]!=c&&(b[a]=c)}),b};c.prototype.enter=function(b){var d=b instanceof this.constructor?b:a(b.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type);
return clearTimeout(d.timeout),d.hoverState="in",d.options.delay&&d.options.delay.show?(d.timeout=setTimeout(function(){"in"==d.hoverState&&d.show()},d.options.delay.show),void 0):d.show()};c.prototype.leave=function(b){var d=b instanceof this.constructor?b:a(b.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type);return clearTimeout(d.timeout),d.hoverState="out",d.options.delay&&d.options.delay.hide?(d.timeout=setTimeout(function(){"out"==d.hoverState&&d.hide()},d.options.delay.hide),
void 0):d.hide()};c.prototype.show=function(){var b=a.Event("show.bs."+this.type);if(this.hasContent()&&this.enabled&&(this.$element.trigger(b),!b.isDefaultPrevented())){var d=this.tip();this.setContent();this.options.animation&&d.addClass("fade");var b="function"==typeof this.options.placement?this.options.placement.call(this,d[0],this.$element[0]):this.options.placement,f=/\s?auto?\s?/i,c=f.test(b);c&&(b=b.replace(f,"")||"top");d.detach().css({top:0,left:0,display:"block"}).addClass(b);this.options.container?
d.appendTo(this.options.container):d.insertAfter(this.$element);var f=this.getPosition(),e=d[0].offsetWidth,l=d[0].offsetHeight;if(c){var n=this.$element.parent(),c=b,t=document.documentElement.scrollTop||document.body.scrollTop,H="body"==this.options.container?window.innerWidth:n.outerWidth(),E="body"==this.options.container?window.innerHeight:n.outerHeight(),n="body"==this.options.container?0:n.offset().left,b="bottom"==b&&f.top+f.height+l-t>E?"top":"top"==b&&0>f.top-t-l?"bottom":"right"==b&&f.right+
e>H?"left":"left"==b&&f.left-e<n?"right":b;d.removeClass(c).addClass(b)}d=this.getCalculatedOffset(b,f,e,l);this.applyPlacement(d,b);this.$element.trigger("shown.bs."+this.type)}};c.prototype.applyPlacement=function(b,a){var f,c=this.tip(),e=c[0].offsetWidth,l=c[0].offsetHeight,n=parseInt(c.css("margin-top"),10),t=parseInt(c.css("margin-left"),10);isNaN(n)&&(n=0);isNaN(t)&&(t=0);b.top+=n;b.left+=t;c.offset(b).addClass("in");n=c[0].offsetWidth;t=c[0].offsetHeight;("top"==a&&t!=l&&(f=!0,b.top=b.top+
l-t),/bottom|top/.test(a))?(l=0,0>b.left&&(l=-2*b.left,b.left=0,c.offset(b),n=c[0].offsetWidth),this.replaceArrow(l-e+n,n,"left")):this.replaceArrow(t-l,t,"top");f&&c.offset(b)};c.prototype.replaceArrow=function(a,d,f){this.arrow().css(f,a?50*(1-a/d)+"%":"")};c.prototype.setContent=function(){var a=this.tip(),d=this.getTitle();a.find(".tooltip-inner")[this.options.html?"html":"text"](d);a.removeClass("fade in top bottom left right")};c.prototype.hide=function(){function b(){"in"!=d.hoverState&&f.detach()}
var d=this,f=this.tip(),c=a.Event("hide.bs."+this.type);return this.$element.trigger(c),c.isDefaultPrevented()?void 0:(f.removeClass("in"),a.support.transition&&this.$tip.hasClass("fade")?f.one(a.support.transition.end,b).emulateTransitionEnd(150):b(),this.$element.trigger("hidden.bs."+this.type),this)};c.prototype.fixTitle=function(){var a=this.$element;(a.attr("title")||"string"!=typeof a.attr("data-original-title"))&&a.attr("data-original-title",a.attr("title")||"").attr("title","")};c.prototype.hasContent=
function(){return this.getTitle()};c.prototype.getPosition=function(){var b=this.$element[0];return a.extend({},"function"==typeof b.getBoundingClientRect?b.getBoundingClientRect():{width:b.offsetWidth,height:b.offsetHeight},this.$element.offset())};c.prototype.getCalculatedOffset=function(a,d,f,c){return"bottom"==a?{top:d.top+d.height,left:d.left+d.width/2-f/2}:"top"==a?{top:d.top-c,left:d.left+d.width/2-f/2}:"left"==a?{top:d.top+d.height/2-c/2,left:d.left-f}:{top:d.top+d.height/2-c/2,left:d.left+
d.width}};c.prototype.getTitle=function(){var a=this.$element,d=this.options;return a.attr("data-original-title")||("function"==typeof d.title?d.title.call(a[0]):d.title)};c.prototype.tip=function(){return this.$tip=this.$tip||a(this.options.template)};c.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".tooltip-arrow")};c.prototype.validate=function(){this.$element[0].parentNode||(this.hide(),this.$element=null,this.options=null)};c.prototype.enable=function(){this.enabled=
!0};c.prototype.disable=function(){this.enabled=!1};c.prototype.toggleEnabled=function(){this.enabled=!this.enabled};c.prototype.toggle=function(b){b=b?a(b.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type):this;b.tip().hasClass("in")?b.leave(b):b.enter(b)};c.prototype.destroy=function(){this.hide().$element.off("."+this.type).removeData("bs."+this.type)};var e=a.fn.tooltip;a.fn.tooltip=function(b){return this.each(function(){var d=a(this),f=d.data("bs.tooltip"),e="object"==
typeof b&&b;f||d.data("bs.tooltip",f=new c(this,e));"string"==typeof b&&f[b]()})};a.fn.tooltip.Constructor=c;a.fn.tooltip.noConflict=function(){return a.fn.tooltip=e,this}}(window.jQuery);
+function(a){var c=function(a,d){this.init("popover",a,d)};if(!a.fn.tooltip)throw Error("Popover requires tooltip.js");c.DEFAULTS=a.extend({},a.fn.tooltip.Constructor.DEFAULTS,{placement:"right",trigger:"click",content:"",template:'<div class="popover"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});c.prototype=a.extend({},a.fn.tooltip.Constructor.prototype);c.prototype.constructor=c;c.prototype.getDefaults=function(){return c.DEFAULTS};c.prototype.setContent=
function(){var a=this.tip(),d=this.getTitle(),f=this.getContent();a.find(".popover-title")[this.options.html?"html":"text"](d);a.find(".popover-content")[this.options.html?"html":"text"](f);a.removeClass("fade top bottom left right in");a.find(".popover-title").html()||a.find(".popover-title").hide()};c.prototype.hasContent=function(){return this.getTitle()||this.getContent()};c.prototype.getContent=function(){var a=this.$element,d=this.options;return a.attr("data-content")||("function"==typeof d.content?
d.content.call(a[0]):d.content)};c.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".arrow")};c.prototype.tip=function(){return this.$tip||(this.$tip=a(this.options.template)),this.$tip};var e=a.fn.popover;a.fn.popover=function(b){return this.each(function(){var d=a(this),f=d.data("bs.popover"),e="object"==typeof b&&b;f||d.data("bs.popover",f=new c(this,e));"string"==typeof b&&f[b]()})};a.fn.popover.Constructor=c;a.fn.popover.noConflict=function(){return a.fn.popover=e,
this}}(window.jQuery);
+function(a){function c(b,d){var f,e=a.proxy(this.process,this);this.$element=a(b).is("body")?a(window):a(b);this.$body=a("body");this.$scrollElement=this.$element.on("scroll.bs.scroll-spy.data-api",e);this.options=a.extend({},c.DEFAULTS,d);this.selector=(this.options.target||(f=a(b).attr("href"))&&f.replace(/.*(?=#[^\s]+$)/,"")||"")+" .nav li > a";this.offsets=a([]);this.targets=a([]);this.activeTarget=null;this.refresh();this.process()}c.DEFAULTS={offset:10};c.prototype.refresh=function(){var b=
this.$element[0]==window?"offset":"position";this.offsets=a([]);this.targets=a([]);var d=this;this.$body.find(this.selector).map(function(){var f=a(this),f=f.data("target")||f.attr("href"),c=/^#\w/.test(f)&&a(f);return c&&c.length&&[[c[b]().top+(!a.isWindow(d.$scrollElement.get(0))&&d.$scrollElement.scrollTop()),f]]||null}).sort(function(a,b){return a[0]-b[0]}).each(function(){d.offsets.push(this[0]);d.targets.push(this[1])})};c.prototype.process=function(){var a,d=this.$scrollElement.scrollTop()+
this.options.offset,c=(this.$scrollElement[0].scrollHeight||this.$body[0].scrollHeight)-this.$scrollElement.height(),e=this.offsets,p=this.targets,l=this.activeTarget;if(d>=c)return l!=(a=p.last()[0])&&this.activate(a);for(a=e.length;a--;)l!=p[a]&&d>=e[a]&&(!e[a+1]||d<=e[a+1])&&this.activate(p[a])};c.prototype.activate=function(b){this.activeTarget=b;a(this.selector).parents(".active").removeClass("active");b=a(this.selector+'[data-target="'+b+'"],'+this.selector+'[href="'+b+'"]').parents("li").addClass("active");
b.parent(".dropdown-menu").length&&(b=b.closest("li.dropdown").addClass("active"));b.trigger("activate")};var e=a.fn.scrollspy;a.fn.scrollspy=function(b){return this.each(function(){var d=a(this),f=d.data("bs.scrollspy"),e="object"==typeof b&&b;f||d.data("bs.scrollspy",f=new c(this,e));"string"==typeof b&&f[b]()})};a.fn.scrollspy.Constructor=c;a.fn.scrollspy.noConflict=function(){return a.fn.scrollspy=e,this};a(window).on("load",function(){a('[data-spy="scroll"]').each(function(){var b=a(this);b.scrollspy(b.data())})})}(window.jQuery);
+function(a){var c=function(b){this.element=a(b)};c.prototype.show=function(){var b=this.element,d=b.closest("ul:not(.dropdown-menu)"),c=b.attr("data-target");if(c||(c=b.attr("href"),c=c&&c.replace(/.*(?=#[^\s]*$)/,"")),!b.parent("li").hasClass("active")){var e=d.find(".active:last a")[0],p=a.Event("show.bs.tab",{relatedTarget:e});(b.trigger(p),p.isDefaultPrevented())||(c=a(c),this.activate(b.parent("li"),d),this.activate(c,c.parent(),function(){b.trigger({type:"shown.bs.tab",relatedTarget:e})}))}};
c.prototype.activate=function(b,d,c){function e(){p.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");b.addClass("active");l?(b[0].offsetWidth,b.addClass("in")):b.removeClass("fade");b.parent(".dropdown-menu")&&b.closest("li.dropdown").addClass("active");c&&c()}var p=d.find("> .active"),l=c&&a.support.transition&&p.hasClass("fade");l?p.one(a.support.transition.end,e).emulateTransitionEnd(150):e();p.removeClass("in")};var e=a.fn.tab;a.fn.tab=function(b){return this.each(function(){var d=
a(this),f=d.data("bs.tab");f||d.data("bs.tab",f=new c(this));"string"==typeof b&&f[b]()})};a.fn.tab.Constructor=c;a.fn.tab.noConflict=function(){return a.fn.tab=e,this};a(document).on("click.bs.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(b){b.preventDefault();a(this).tab("show")})}(window.jQuery);
+function(a){var c=function(b,d){this.options=a.extend({},c.DEFAULTS,d);this.$window=a(window).on("scroll.bs.affix.data-api",a.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",a.proxy(this.checkPositionWithEventLoop,this));this.$element=a(b);this.affixed=this.unpin=null;this.checkPosition()};c.RESET="affix affix-top affix-bottom";c.DEFAULTS={offset:0};c.prototype.checkPositionWithEventLoop=function(){setTimeout(a.proxy(this.checkPosition,this),1)};c.prototype.checkPosition=function(){if(this.$element.is(":visible")){var b=
a(document).height(),d=this.$window.scrollTop(),f=this.$element.offset(),e=this.options.offset,p=e.top,l=e.bottom;"object"!=typeof e&&(l=p=e);"function"==typeof p&&(p=e.top());"function"==typeof l&&(l=e.bottom());b=null!=this.unpin&&d+this.unpin<=f.top?!1:null!=l&&f.top+this.$element.height()>=b-l?"bottom":null!=p&&p>=d?"top":!1;this.affixed!==b&&(this.unpin&&this.$element.css("top",""),this.affixed=b,this.unpin="bottom"==b?f.top-d:null,this.$element.removeClass(c.RESET).addClass("affix"+(b?"-"+b:
"")),"bottom"==b&&this.$element.offset({top:document.body.offsetHeight-l-this.$element.height()}))}};var e=a.fn.affix;a.fn.affix=function(b){return this.each(function(){var d=a(this),f=d.data("bs.affix"),e="object"==typeof b&&b;f||d.data("bs.affix",f=new c(this,e));"string"==typeof b&&f[b]()})};a.fn.affix.Constructor=c;a.fn.affix.noConflict=function(){return a.fn.affix=e,this};a(window).on("load",function(){a('[data-spy="affix"]').each(function(){var b=a(this),d=b.data();d.offset=d.offset||{};d.offsetBottom&&
(d.offset.bottom=d.offsetBottom);d.offsetTop&&(d.offset.top=d.offsetTop);b.affix(d)})})}(window.jQuery);(function(a){function c(b){var d=b||window.event,c=[].slice.call(arguments,1),e=0,p=0,l=0;b=a.event.fix(d);b.type="mousewheel";b.wheelDelta&&(e=b.wheelDelta/120);b.detail&&(e=-b.detail/3);l=e;void 0!==d.axis&&d.axis===d.HORIZONTAL_AXIS&&(l=0,p=-1*e);void 0!==d.wheelDeltaY&&(l=d.wheelDeltaY/120);void 0!==d.wheelDeltaX&&(p=-1*d.wheelDeltaX/120);c.unshift(b,e,p,l);return a.event.handle.apply(this,c)}var e=["DOMMouseScroll","mousewheel"];a.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=
e.length;a;)this.addEventListener(e[--a],c,!1);else this.onmousewheel=c},teardown:function(){if(this.removeEventListener)for(var a=e.length;a;)this.removeEventListener(e[--a],c,!1);else this.onmousewheel=null}};a.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);(function(a,c,e){a.fn.jScrollPane=function(b){function d(b,d){function c(d){var g,h,k,w,oa,ua=!1,n=!1;m=d;if(r===e)w=b.scrollTop(),oa=b.scrollLeft(),b.css({overflow:"hidden",padding:0}),v=b.innerWidth()+W,u=b.innerHeight(),b.width(v),r=a('<div class="jspPane" />').css("padding",va).append(b.children()),s=a('<div class="jspContainer" />').css({width:v+"px",height:u+"px"}).append(r).appendTo(b);else{b.css("width","");ua=m.stickToBottom&&za();n=m.stickToRight&&Aa();if(k=b.innerWidth()+W!=v||b.outerHeight()!=
u)v=b.innerWidth()+W,u=b.innerHeight(),s.css({width:v+"px",height:u+"px"});if(!k&&wa==D&&r.outerHeight()==C){b.width(v);return}wa=D;r.css("width","");b.width(v);s.find(">.jspVerticalBar,>.jspHorizontalBar").remove().end()}r.css("overflow","auto");D=d.contentWidth?d.contentWidth:r[0].scrollWidth;C=r[0].scrollHeight;r.css("overflow","");pa=D/v;ga=C/u;I=1<ga;if((J=1<pa)||I){b.addClass("jspScrollable");if(d=m.maintainPosition&&(A||B))g=P(),h=Q();l();t();E();d&&(X(n?D-v:g,!1),R(ua?C-u:h,!1));Ba();Ca();
Da();m.enableKeyboardNavigation&&Ea();m.clickOnTrack&&q();Fa();m.hijackInternalLinks&&xa()}else b.removeClass("jspScrollable"),r.css({top:0,width:s.width()-W}),s.unbind(qa),r.find(":input,a").unbind("focus.jsp"),b.attr("tabindex","-1").removeAttr("tabindex").unbind("keydown.jsp keypress.jsp"),y(),ya();m.autoReinitialise&&!ha?ha=setInterval(function(){c(m)},m.autoReinitialiseDelay):!m.autoReinitialise&&ha&&clearInterval(ha);w&&b.scrollTop(0)&&R(w,!1);oa&&b.scrollLeft(0)&&X(oa,!1);b.trigger("jsp-initialised",
[J||I])}function l(){I&&(s.append(a('<div class="jspVerticalBar" />').append(a('<div class="jspCap jspCapTop" />'),a('<div class="jspTrack" />').append(a('<div class="jspDrag" />').append(a('<div class="jspDragTop" />'),a('<div class="jspDragBottom" />'))),a('<div class="jspCap jspCapBottom" />'))),ia=s.find(">.jspVerticalBar"),M=ia.find(">.jspTrack"),F=M.find(">.jspDrag"),m.showArrows&&(aa=a('<a class="jspArrow jspArrowUp" />').bind("mousedown.jsp",h(0,-1)).bind("click.jsp",Y),ba=a('<a class="jspArrow jspArrowDown" />').bind("mousedown.jsp",
h(0,1)).bind("click.jsp",Y),m.arrowScrollOnHover&&(aa.bind("mouseover.jsp",h(0,-1,aa)),ba.bind("mouseover.jsp",h(0,1,ba))),g(M,m.verticalArrowPositions,aa,ba)),S=u,s.find(">.jspVerticalBar>.jspCap:visible,>.jspVerticalBar>.jspArrow").each(function(){S-=a(this).outerHeight()}),F.hover(function(){F.addClass("jspHover")},function(){F.removeClass("jspHover")}).bind("mousedown.jsp",function(b){a("html").bind("dragstart.jsp selectstart.jsp",Y);F.addClass("jspActive");var d=b.pageY-F.position().top;a("html").bind("mousemove.jsp",
function(a){k(a.pageY-d,!1)}).bind("mouseup.jsp mouseleave.jsp",ca);return!1}),n())}function n(){M.height(S+"px");A=0;ra=m.verticalGutter+M.outerWidth();r.width(v-ra-W);try{0===ia.position().left&&r.css("margin-left",ra+"px")}catch(a){}}function t(){J&&(s.append(a('<div class="jspHorizontalBar" />').append(a('<div class="jspCap jspCapLeft" />'),a('<div class="jspTrack" />').append(a('<div class="jspDrag" />').append(a('<div class="jspDragLeft" />'),a('<div class="jspDragRight" />'))),a('<div class="jspCap jspCapRight" />'))),
ja=s.find(">.jspHorizontalBar"),N=ja.find(">.jspTrack"),G=N.find(">.jspDrag"),m.showArrows&&(da=a('<a class="jspArrow jspArrowLeft" />').bind("mousedown.jsp",h(-1,0)).bind("click.jsp",Y),ea=a('<a class="jspArrow jspArrowRight" />').bind("mousedown.jsp",h(1,0)).bind("click.jsp",Y),m.arrowScrollOnHover&&(da.bind("mouseover.jsp",h(-1,0,da)),ea.bind("mouseover.jsp",h(1,0,ea))),g(N,m.horizontalArrowPositions,da,ea)),G.hover(function(){G.addClass("jspHover")},function(){G.removeClass("jspHover")}).bind("mousedown.jsp",
function(b){a("html").bind("dragstart.jsp selectstart.jsp",Y);G.addClass("jspActive");var d=b.pageX-G.position().left;a("html").bind("mousemove.jsp",function(a){Z(a.pageX-d,!1)}).bind("mouseup.jsp mouseleave.jsp",ca);return!1}),K=s.innerWidth(),H())}function H(){s.find(">.jspHorizontalBar>.jspCap:visible,>.jspHorizontalBar>.jspArrow").each(function(){K-=a(this).outerWidth()});N.width(K+"px");B=0}function E(){if(J&&I){var b=N.outerHeight(),d=M.outerWidth();S-=b;a(ja).find(">.jspCap:visible,>.jspArrow").each(function(){K+=
a(this).outerWidth()});K-=d;u-=d;v-=b;N.parent().append(a('<div class="jspCorner" />').css("width",b+"px"));n();H()}J&&r.width(s.outerWidth()-W+"px");C=r.outerHeight();ga=C/u;J&&(T=Math.ceil(1/pa*K),T>m.horizontalDragMaxWidth?T=m.horizontalDragMaxWidth:T<m.horizontalDragMinWidth&&(T=m.horizontalDragMinWidth),G.width(T+"px"),U=K-T,sa(B));I&&(V=Math.ceil(1/ga*S),V>m.verticalDragMaxHeight?V=m.verticalDragMaxHeight:V<m.verticalDragMinHeight&&(V=m.verticalDragMinHeight),F.height(V+"px"),O=S-V,w(A))}function g(a,
b,d,c){var e="before",f="after";"os"==b&&(b=/Mac/.test(navigator.platform)?"after":"split");b==e?f=b:b==f&&(e=b,b=d,d=c,c=b);a[e](d)[f](c)}function h(a,b,d){return function(){L(a,b,this,d);this.blur();return!1}}function L(b,d,c,e){c=a(c).addClass("jspActive");var f,g,h=!0,k=function(){0!==b&&z.scrollByX(b*m.arrowButtonSpeed);0!==d&&z.scrollByY(d*m.arrowButtonSpeed);g=setTimeout(k,h?m.initialDelay:m.arrowRepeatFreq);h=!1};k();f=e?"mouseout.jsp":"mouseup.jsp";e=e||a("html");e.bind(f,function(){c.removeClass("jspActive");
g&&clearTimeout(g);g=null;e.unbind(f)})}function q(){y();I&&M.bind("mousedown.jsp",function(b){if(b.originalTarget===e||b.originalTarget==b.currentTarget){var d=a(this),c=d.offset(),f=b.pageY-c.top-A,g,h=!0,w=function(){var a=d.offset(),a=b.pageY-a.top-V/2,c=u*m.scrollPagePercent,e=O*c/(C-u);if(0>f)A-e>a?z.scrollByY(-c):k(a);else if(0<f)A+e<a?z.scrollByY(c):k(a);else{l();return}g=setTimeout(w,h?m.initialDelay:m.trackClickRepeatFreq);h=!1},l=function(){g&&clearTimeout(g);g=null;a(document).unbind("mouseup.jsp",
l)};w();a(document).bind("mouseup.jsp",l);return!1}});J&&N.bind("mousedown.jsp",function(b){if(b.originalTarget===e||b.originalTarget==b.currentTarget){var d=a(this),c=d.offset(),f=b.pageX-c.left-B,g,h=!0,k=function(){var a=d.offset(),a=b.pageX-a.left-T/2,c=v*m.scrollPagePercent,e=U*c/(D-v);if(0>f)B-e>a?z.scrollByX(-c):Z(a);else if(0<f)B+e<a?z.scrollByX(c):Z(a);else{w();return}g=setTimeout(k,h?m.initialDelay:m.trackClickRepeatFreq);h=!1},w=function(){g&&clearTimeout(g);g=null;a(document).unbind("mouseup.jsp",
w)};k();a(document).bind("mouseup.jsp",w);return!1}})}function y(){N&&N.unbind("mousedown.jsp");M&&M.unbind("mousedown.jsp")}function ca(){a("html").unbind("dragstart.jsp selectstart.jsp mousemove.jsp mouseup.jsp mouseleave.jsp");F&&F.removeClass("jspActive");G&&G.removeClass("jspActive")}function k(a,b){I&&(0>a?a=0:a>O&&(a=O),b===e&&(b=m.animateScroll),b?z.animate(F,"top",a,w):(F.css("top",a),w(a)))}function w(a){a===e&&(a=F.position().top);s.scrollTop(0);A=a;var d=0===A,c=A==O;a=-(a/O)*(C-u);if(ka!=
d||la!=c)ka=d,la=c,b.trigger("jsp-arrow-change",[ka,la,ma,na]);m.showArrows&&(aa[d?"addClass":"removeClass"]("jspDisabled"),ba[c?"addClass":"removeClass"]("jspDisabled"));r.css("top",a);b.trigger("jsp-scroll-y",[-a,d,c]).trigger("scroll")}function Z(a,b){J&&(0>a?a=0:a>U&&(a=U),b===e&&(b=m.animateScroll),b?z.animate(G,"left",a,sa):(G.css("left",a),sa(a)))}function sa(a){a===e&&(a=G.position().left);s.scrollTop(0);B=a;var d=0===B,c=B==U;a=-(a/U)*(D-v);if(ma!=d||na!=c)ma=d,na=c,b.trigger("jsp-arrow-change",
[ka,la,ma,na]);m.showArrows&&(da[d?"addClass":"removeClass"]("jspDisabled"),ea[c?"addClass":"removeClass"]("jspDisabled"));r.css("left",a);b.trigger("jsp-scroll-x",[-a,d,c]).trigger("scroll")}function R(a,b){k(a/(C-u)*O,b)}function X(a,b){Z(a/(D-v)*U,b)}function fa(b,d,c){var e,f,g=0,h=0,k,w,l;try{e=a(b)}catch(n){return}f=e.outerHeight();b=e.outerWidth();s.scrollTop(0);for(s.scrollLeft(0);!e.is(".jspPane");)if(g+=e.position().top,h+=e.position().left,e=e.offsetParent(),/^body|html$/i.test(e[0].nodeName))return;
e=Q();k=e+u;g<e||d?w=g-m.verticalGutter:g+f>k&&(w=g-u+f+m.verticalGutter);w&&R(w,c);g=P();w=g+v;h<g||d?l=h-m.horizontalGutter:h+b>w&&(l=h-v+b+m.horizontalGutter);l&&X(l,c)}function P(){return-r.position().left}function Q(){return-r.position().top}function za(){var a=C-u;return 20<a&&10>a-Q()}function Aa(){var a=D-v;return 20<a&&10>a-P()}function Ca(){s.unbind(qa).bind(qa,function(a,b,d,c){a=B;b=A;z.scrollBy(d*m.mouseWheelSpeed,-c*m.mouseWheelSpeed,!1);return a==B&&b==A})}function Y(){return!1}function Ba(){r.find(":input,a").unbind("focus.jsp").bind("focus.jsp",
function(a){fa(a.target,!1)})}function Ea(){function d(){var a=B,b=A;switch(c){case 40:z.scrollByY(m.keyboardSpeed,!1);break;case 38:z.scrollByY(-m.keyboardSpeed,!1);break;case 34:case 32:z.scrollByY(u*m.scrollPagePercent,!1);break;case 33:z.scrollByY(-u*m.scrollPagePercent,!1);break;case 39:z.scrollByX(m.keyboardSpeed,!1);break;case 37:z.scrollByX(-m.keyboardSpeed,!1)}return e=a!=B||b!=A}var c,e,g=[];J&&g.push(ja[0]);I&&g.push(ia[0]);r.focus(function(){b.focus()});b.attr("tabindex",0).unbind("keydown.jsp keypress.jsp").bind("keydown.jsp",
function(b){if(b.target===this||g.length&&a(b.target).closest(g).length){var f=B,h=A;switch(b.keyCode){case 40:case 38:case 34:case 32:case 33:case 39:case 37:c=b.keyCode;d();break;case 35:R(C-u);c=null;break;case 36:R(0),c=null}e=b.keyCode==c&&f!=B||h!=A;return!e}}).bind("keypress.jsp",function(a){a.keyCode==c&&d();return!e});m.hideFocus?(b.css("outline","none"),"hideFocus"in s[0]&&b.attr("hideFocus",!0)):(b.css("outline",""),"hideFocus"in s[0]&&b.attr("hideFocus",!1))}function Fa(){if(location.hash&&
1<location.hash.length){var b,d,c=escape(location.hash);try{b=a(c)}catch(e){return}b.length&&r.find(c)&&(0===s.scrollTop()?d=setInterval(function(){0<s.scrollTop()&&(fa(c,!0),a(document).scrollTop(s.position().top),clearInterval(d))},50):(fa(c,!0),a(document).scrollTop(s.position().top)))}}function ya(){a("a.jspHijack").unbind("click.jsp-hijack").removeClass("jspHijack")}function xa(){ya();a("a[href^=#]").addClass("jspHijack").bind("click.jsp-hijack",function(){var a=this.href.split("#");if(1<a.length&&
(a=a[1],0<a.length&&0<r.find("#"+a).length))return fa("#"+a,!0),!1})}function Da(){var a,b,d,c,e,f=!1;s.unbind("touchstart.jsp touchmove.jsp touchend.jsp click.jsp-touchclick").bind("touchstart.jsp",function(g){g=g.originalEvent.touches[0];a=P();b=Q();d=g.pageX;c=g.pageY;e=!1;f=!0}).bind("touchmove.jsp",function(g){if(f){g=g.originalEvent.touches[0];var h=B,w=A;z.scrollTo(a+d-g.pageX,b+c-g.pageY);e=e||5<Math.abs(d-g.pageX)||5<Math.abs(c-g.pageY);return h==B&&w==A}}).bind("touchend.jsp",function(a){f=
!1}).bind("click.jsp-touchclick",function(a){if(e)return e=!1})}var m,z=this,r,v,u,s,D,C,pa,ga,I,J,F,O,A,G,U,B,ia,M,ra,S,V,aa,ba,ja,N,K,T,da,ea,ha,va,W,wa,ka=!0,ma=!0,la=!1,na=!1,ta=b.clone(!1,!1).empty(),qa=a.fn.mwheelIntent?"mwheelIntent.jsp":"mousewheel.jsp";va=b.css("paddingTop")+" "+b.css("paddingRight")+" "+b.css("paddingBottom")+" "+b.css("paddingLeft");W=(parseInt(b.css("paddingLeft"),10)||0)+(parseInt(b.css("paddingRight"),10)||0);a.extend(z,{reinitialise:function(b){b=a.extend({},m,b);c(b)},
scrollToElement:function(a,b,d){fa(a,b,d)},scrollTo:function(a,b,d){X(a,d);R(b,d)},scrollToX:function(a,b){X(a,b)},scrollToY:function(a,b){R(a,b)},scrollToPercentX:function(a,b){X(a*(D-v),b)},scrollToPercentY:function(a,b){R(a*(C-u),b)},scrollBy:function(a,b,d){z.scrollByX(a,d);z.scrollByY(b,d)},scrollByX:function(a,b){var d=(P()+Math[0>a?"floor":"ceil"](a))/(D-v);Z(d*U,b)},scrollByY:function(a,b){var d=(Q()+Math[0>a?"floor":"ceil"](a))/(C-u);k(d*O,b)},positionDragX:function(a,b){Z(a,b)},positionDragY:function(a,
b){k(a,b)},animate:function(a,b,d,c){var e={};e[b]=d;a.animate(e,{duration:m.animateDuration,easing:m.animateEase,queue:!1,step:c})},getContentPositionX:function(){return P()},getContentPositionY:function(){return Q()},getContentWidth:function(){return D},getContentHeight:function(){return C},getPercentScrolledX:function(){return P()/(D-v)},getPercentScrolledY:function(){return Q()/(C-u)},getIsScrollableH:function(){return J},getIsScrollableV:function(){return I},getContentPane:function(){return r},
scrollToBottom:function(a){k(O,a)},hijackInternalLinks:function(){xa()},destroy:function(){var a=Q(),d=P();b.removeClass("jspScrollable").unbind(".jsp");b.replaceWith(ta.append(r.children()));ta.scrollTop(a);ta.scrollLeft(d)}});c(d)}b=a.extend({},a.fn.jScrollPane.defaults,b);a.each(["mouseWheelSpeed","arrowButtonSpeed","trackClickSpeed","keyboardSpeed"],function(){b[this]=b[this]||b.speed});return this.each(function(){var c=a(this),e=c.data("jsp");e?e.reinitialise(b):(e=new d(c,b),c.data("jsp",e))})};
a.fn.jScrollPane.defaults={showArrows:!1,maintainPosition:!0,stickToBottom:!1,stickToRight:!1,clickOnTrack:!0,autoReinitialise:!1,autoReinitialiseDelay:500,verticalDragMinHeight:0,verticalDragMaxHeight:99999,horizontalDragMinWidth:0,horizontalDragMaxWidth:99999,contentWidth:e,animateScroll:!1,animateDuration:300,animateEase:"linear",hijackInternalLinks:!1,verticalGutter:4,horizontalGutter:4,mouseWheelSpeed:0,arrowButtonSpeed:0,arrowRepeatFreq:50,arrowScrollOnHover:!1,trackClickSpeed:0,trackClickRepeatFreq:70,
verticalArrowPositions:"split",horizontalArrowPositions:"split",enableKeyboardNavigation:!0,hideFocus:!1,keyboardSpeed:0,initialDelay:300,speed:30,scrollPagePercent:0.8}})(jQuery,this);(function(a){var c=0;a.fn.splitter=function(e){e=e||{};return this.each(function(){function b(){return a.browser.msie&&9>parseInt(a.browser.version)}function d(a){k.removeClass(g.barStateClasses).addClass(a)}function f(b){1==b.which&&(k.removeClass(g.barHoverClass),g.outline&&(H=H||k.clone(!1).insertAfter(q),k.removeClass(g.barDockedClass)),d(g.barActiveClass),L.css("-webkit-user-select","none").find("iframe").addClass(g.iframeClass),q._posSplit=q[0][g.pxSplit]-b[g.eventPos],a(document).bind("mousemove"+
g.eventNamespace,x).bind("mouseup"+g.eventNamespace,p))}function x(a){a=q._posSplit+a[g.eventPos];var b=Math.max(0,Math.min(a,h._DA-k._DA)),c=Math.max(q._min,h._DA-y._max,Math.min(a,q._max,h._DA-k._DA-y._min));g.outline?(g.dockPane==q&&a<Math.max(q._min,k._DA)||g.dockPane==y&&a>Math.min(a,q._max,h._DA-k._DA-y._min)?k.addClass(g.barDockedClass).css(g.origin,b):k.removeClass(g.barDockedClass).css(g.origin,c),k._DA=k[0][g.pxSplit]):l(a);d(a==c?g.barActiveClass:g.barLimitClass)}function p(b){d(g.barNormalClass);
k.addClass(g.barHoverClass);b=q._posSplit+b[g.eventPos];g.outline&&(H&&H.remove(),H=null,l(b));L.css("-webkit-user-select","text").find("iframe").removeClass(g.iframeClass);a(document).unbind("mousemove"+g.eventNamespace+" mouseup"+g.eventNamespace)}function l(a){k._DA=k[0][g.pxSplit];g.dockPane==q&&a<Math.max(q._min,k._DA)||g.dockPane==y&&a>Math.min(a,q._max,h._DA-k._DA-y._min)?(k.addClass(g.barDockedClass),k._DA=k[0][g.pxSplit],a=g.dockPane==q?0:h._DA-k._DA,null==k._pos&&(k._pos=q[0][g.pxSplit])):
(k.removeClass(g.barDockedClass),k._DA=k[0][g.pxSplit],k._pos=null,a=Math.max(q._min,h._DA-y._max,Math.min(a,q._max,h._DA-k._DA-y._min)));k.css(g.origin,a).css(g.fixed,h._DF);q.css(g.origin,0).css(g.split,a).css(g.fixed,h._DF);y.css(g.origin,a+k._DA).css(g.split,h._DA-k._DA-a).css(g.fixed,h._DF);b()||L.trigger("resize")}function n(a,b){for(var d=0,c=1;c<arguments.length;c++)d+=Math.max(parseInt(a.css(arguments[c]),10)||0,0);return d}function t(a){h._DF=h[0][g.pxFixed]-h._PBF;h._DA=h[0][g.pxSplit]-
h._PBA;0>=h._DF||0>=h._DA||h._oldW==h.width()&&h._oldH==h.height()||(h._oldW=h.width(),h._oldH=h.height(),l(isNaN(a)?g.sizeRight||g.sizeBottom?h._DA-y[0][g.pxSplit]-k._DA:q[0][g.pxSplit]:a),d(g.barNormalClass))}if(!a(this).attr("data-splitter-initialized")){var H,E=(e.splitHorizontal?"h":e.splitVertical?"v":e.type)||"v",g=a.extend({splitterClass:"splitter ui-widget ui-widget-content",paneClass:"splitter-pane",barClass:"splitter-bar",barNormalClass:"ui-state-default",barHoverClass:"ui-state-hover",
barActiveClass:"ui-state-highlight",barLimitClass:"ui-state-error",iframeClass:"splitter-iframe-hide",eventNamespace:".splitter"+ ++c,pxPerKey:8,tabIndex:0,accessKey:""},{v:{keyLeft:39,keyRight:37,cursor:"e-resize",barStateClass:"splitter-bar-vertical",barDockedClass:"splitter-bar-vertical-docked"},h:{keyTop:40,keyBottom:38,cursor:"n-resize",barStateClass:"splitter-bar-horizontal",barDockedClass:"splitter-bar-horizontal-docked"}}[E],e,{v:{type:"v",eventPos:"pageX",origin:"left",split:"width",pxSplit:"offsetWidth",
side1:"Left",side2:"Right",fixed:"height",pxFixed:"offsetHeight",side3:"Top",side4:"Bottom"},h:{type:"h",eventPos:"pageY",origin:"top",split:"height",pxSplit:"offsetHeight",side1:"Top",side2:"Bottom",fixed:"width",pxFixed:"offsetWidth",side3:"Left",side4:"Right"}}[E]);g.barStateClasses=[g.barNormalClass,g.barHoverClass,g.barActiveClass,g.barLimitClass].join(" ");var h=a(this).css({position:"relative"}).addClass(g.splitterClass).attr("data-splitter-initialized",!0),L=a(">*",h[0]).addClass(g.paneClass).css({position:"absolute",
"z-index":"1","-moz-outline-style":"none"}),q=a(L[0]),y=a(L[1]);g.dockPane=g.dock&&(/right|bottom/.test(g.dock)?y:q);var ca=a('<a href="javascript:void(0)"></a>').attr({accessKey:g.accessKey,tabIndex:g.tabIndex,title:g.splitbarClass}).bind((a.browser.opera?"click":"focus")+g.eventNamespace,function(){this.focus();k.addClass(g.barActiveClass)}).bind("keydown"+g.eventNamespace,function(a){a=a.which||a.keyCode;(a=a==g["key"+g.side1]?1:a==g["key"+g.side2]?-1:0)&&l(q[0][g.pxSplit]+a*g.pxPerKey,!1)}).bind("blur"+
g.eventNamespace,function(){k.removeClass(g.barActiveClass)}),k=a("<div></div>").insertAfter(q).addClass(g.barClass).addClass(g.barStateClass).append(ca).attr({unselectable:"on"}).css({position:"absolute","user-select":"none","-webkit-user-select":"none","-khtml-user-select":"none","-moz-user-select":"none","z-index":"100"}).bind("mousedown"+g.eventNamespace,f).bind("mouseover"+g.eventNamespace,function(){a(this).addClass(g.barHoverClass)}).bind("mouseout"+g.eventNamespace,function(){a(this).removeClass(g.barHoverClass)});
/^(auto|default|)$/.test(k.css("cursor"))&&k.css("cursor",g.cursor);k._DA=k[0][g.pxSplit];h._PBF=n(h,"border"+g.side3+"Width","border"+g.side4+"Width");h._PBA=n(h,"border"+g.side1+"Width","border"+g.side2+"Width");q._pane=g.side1;y._pane=g.side2;a.each([q,y],function(){this._splitter_style=this.style;this._min=g["min"+this._pane]||n(this,"min-"+g.split);this._max=g["max"+this._pane]||n(this,"max-"+g.split)||9999;this._init=!0===g["size"+this._pane]?parseInt(a.css(this[0],g.split),10):g["size"+this._pane]});
E=q._init;isNaN(y._init)||(E=h[0][g.pxSplit]-h._PBA-y._init-k._DA);g.cookie&&(a.cookie||alert("jQuery.splitter(): jQuery cookie plugin required"),null!=a.cookie(g.cookie)&&(E=parseInt(a.cookie(g.cookie),10)),a(window).bind("unload"+g.eventNamespace,function(){var b=String(k.css(g.origin));a.cookie(g.cookie,b,{expires:g.cookieExpires||365,path:g.cookiePath||document.location.pathname})}));isNaN(E)&&(E=Math.round((h[0][g.pxSplit]-h._PBA-k._DA)/2));g.anchorToWindow&&(g.resizeTo=window);g.resizeTo?(h._hadjust=
n(h,"borderTopWidth","borderBottomWidth","marginBottom"),h._hmin=Math.max(n(h,"minHeight"),20),a(window).bind("resize"+g.eventNamespace,function(){var d=h.offset().top,c=a(g.resizeTo).height();h.css("height",Math.max(c-d-h._hadjust,h._hmin)+"px");b()||h.triggerHandler("resize")}).triggerHandler("resize"+g.eventNamespace)):g.resizeToWidth&&!b()&&a(window).bind("resize"+g.eventNamespace,function(){t()});g.dock&&(h.bind("toggleDock"+g.eventNamespace,function(){h.triggerHandler(g.dockPane[0][g.pxSplit]?
"dock":"undock")}).bind("dock"+g.eventNamespace,function(){var a=q[0][g.pxSplit];if(a){k._pos=a;var b={};b[g.origin]=g.dockPane==q?0:h[0][g.pxSplit]-h._PBA-k[0][g.pxSplit];k.animate(b,g.dockSpeed||1,g.dockEasing,function(){k.addClass(g.barDockedClass);l(b[g.origin])})}}).bind("undock"+g.eventNamespace,function(){if(!g.dockPane[0][g.pxSplit]){var a={};a[g.origin]=k._pos+"px";k.removeClass(g.barDockedClass).animate(a,g.undockSpeed||g.dockSpeed||1,g.undockEasing||g.dockEasing,function(){l(k._pos);k._pos=
null})}}),g.dockKey&&a('<a title="'+g.splitbarClass+' toggle dock" href="javascript:void(0)"></a>').attr({accessKey:g.dockKey,tabIndex:-1}).appendTo(k).bind(a.browser.opera?"click":"focus",function(){h.triggerHandler("toggleDock");this.blur()}),k.bind("dblclick",function(){h.triggerHandler("toggleDock")}));h.bind("destroy"+g.eventNamespace,function(){a([window,document]).unbind(g.eventNamespace);k.unbind().remove();L.removeClass(g.paneClass);h.removeClass(g.splitterClass).add(L).unbind(g.eventNamespace).attr("style",
function(a){return this._splitter_style||""});h=k=ca=L=q=y=g=e=null}).bind("resize"+g.eventNamespace,function(a,b){t(b)}).trigger("resize",[E])}})}})(jQuery);"ace"in window||(window.ace={});jQuery(function(a){window.ace.click_event=a.fn.tap?"tap":"click"});jQuery(function(a){ace.handle_side_menu(jQuery);ace.enable_search_ahead(jQuery);ace.general_things(jQuery);ace.widget_boxes(jQuery);ace.widget_reload_handler(jQuery)});
ace.handle_side_menu=function(a){a("#menu-toggler").on(ace.click_event,function(){a("#sidebar").toggleClass("display");a(this).toggleClass("display");return!1});var c=a("#sidebar").hasClass("menu-min");a("#sidebar-collapse").on(ace.click_event,function(){c=a("#sidebar").hasClass("menu-min");ace.settings.sidebar_collapsed(!c)});a(".nav-list").on(ace.click_event,function(e){var b=a(e.target).closest("a");if(b&&0!=b.length){c=a("#sidebar").hasClass("menu-min");if(b.hasClass("dropdown-toggle")){var d=
b.next().get(0);if(!a(d).is(":visible")){e=a(d.parentNode).closest("ul");if(c&&e.hasClass("nav-list"))return;e.find("> .open > .submenu").each(function(){this==d||a(this.parentNode).hasClass("active")||a(this).slideUp(200).parent().removeClass("open")})}if(c&&a(d.parentNode.parentNode).hasClass("nav-list"))return!1;a(d).slideToggle(200).parent().toggleClass("open");return!1}if(c&&"tap"==ace.click_event&&b.get(0).parentNode.parentNode==this&&(b=b.find(".menu-text").get(0),e.target!=b&&!a.contains(b,
e.target)))return!1}})};
ace.general_things=function(a){a('.ace-nav [class*="icon-animated-"]').closest("a").on("click",function(){var c=a(this).find('[class*="icon-animated-"]').eq(0),b=c.attr("class").match(/icon\-animated\-([\d\w]+)/);c.removeClass(b[0]);a(this).off("click")});a(".nav-list .badge[title],.nav-list .label[title]").tooltip({placement:"right"});a("#ace-settings-btn").on(ace.click_event,function(){a(this).toggleClass("open");a("#ace-settings-box").toggleClass("open")});a("#ace-settings-navbar").on("click",function(){ace.settings.navbar_fixed(this.checked)}).each(function(){this.checked=
ace.settings.is("navbar","fixed")});a("#ace-settings-sidebar").on("click",function(){ace.settings.sidebar_fixed(this.checked)}).each(function(){this.checked=ace.settings.is("sidebar","fixed")});a("#ace-settings-breadcrumbs").on("click",function(){ace.settings.breadcrumbs_fixed(this.checked)}).each(function(){this.checked=ace.settings.is("breadcrumbs","fixed")});a("#ace-settings-add-container").on("click",function(){ace.settings.main_container_fixed(this.checked)}).each(function(){this.checked=ace.settings.is("main-container",
"fixed")});a("#ace-settings-rtl").removeAttr("checked").on("click",function(){ace.switch_direction(jQuery)});a("#btn-scroll-up").on(ace.click_event,function(){var c=Math.min(400,Math.max(100,parseInt(a("html").scrollTop()/3)));a("html,body").animate({scrollTop:0},c);return!1});try{a("#skin-colorpicker").ace_colorpicker()}catch(c){}a("#skin-colorpicker").on("change",function(){var c=a(this).find("option:selected").data("skin"),b=a(document.body);b.removeClass("skin-1 skin-2 skin-3");"default"!=c&&
b.addClass(c);"skin-1"==c?a(".ace-nav > li.grey").addClass("dark"):a(".ace-nav > li.grey").removeClass("dark");"skin-2"==c?(a(".ace-nav > li").addClass("no-border margin-1"),a(".ace-nav > li:not(:last-child)").addClass("light-pink").find('> a > [class*="icon-"]').addClass("pink").end().eq(0).find(".badge").addClass("badge-warning")):(a(".ace-nav > li").removeClass("no-border margin-1"),a(".ace-nav > li:not(:last-child)").removeClass("light-pink").find('> a > [class*="icon-"]').removeClass("pink").end().eq(0).find(".badge").removeClass("badge-warning"));
"skin-3"==c?a(".ace-nav > li.grey").addClass("red").find(".badge").addClass("badge-yellow"):a(".ace-nav > li.grey").removeClass("red").find(".badge").removeClass("badge-yellow")})};
ace.widget_boxes=function(a){a(document).on("hide.bs.collapse show.bs.collapse",function(c){var e=c.target.getAttribute("id");a('[href*="#'+e+'"]').find('[class*="icon-"]').each(function(){var b=a(this),d,e=null,x=null;if(e=b.attr("data-icon-show"))x=b.attr("data-icon-hide");else if(d=b.attr("class").match(/icon\-(.*)\-(up|down)/))e="icon-"+d[1]+"-down",x="icon-"+d[1]+"-up";if(e)return"show"==c.type?b.removeClass(e).addClass(x):b.removeClass(x).addClass(e),!1})});a(document).on("click.ace.widget",
"[data-action]",function(c){c.preventDefault();var e=a(this);c=e.data("action");var b=e.closest(".widget-box");if(!b.hasClass("ui-sortable-helper"))if("collapse"==c){c=b.hasClass("collapsed")?"show":"hide";var d="show"==c?"shown":"hidden",f;b.trigger(f=a.Event(c+".ace.widget"));if(!f.isDefaultPrevented()){var x=b.find(".widget-body"),e=e.find("[class*=icon-]").eq(0),p=e.attr("class").match(/icon\-(.*)\-(up|down)/),l="icon-"+p[1]+"-down",p="icon-"+p[1]+"-up",n=x.find(".widget-body-inner"),x=0==n.length?
x.wrapInner('<div class="widget-body-inner"></div>').find(":first-child").eq(0):n.eq(0);"show"==c?(e&&e.addClass(p).removeClass(l),b.removeClass("collapsed"),x.slideUp(0,function(){x.slideDown(300,function(){b.trigger(f=a.Event(d+".ace.widget"))})})):(e&&e.addClass(l).removeClass(p),x.slideUp(200,function(){b.addClass("collapsed");b.trigger(f=a.Event(d+".ace.widget"))}))}}else if("close"==c)b.trigger(f=a.Event("close.ace.widget")),f.isDefaultPrevented()||(c=parseInt(e.data("close-speed"))||300,b.hide(c,
function(){b.trigger(f=a.Event("closed.ace.widget"));b.remove()}));else if("reload"==c){if(b.trigger(f=a.Event("reload.ace.widget")),!f.isDefaultPrevented()){e.blur();var t=!1;"static"==b.css("position")&&(t=!0,b.addClass("position-relative"));b.append('<div class="widget-box-overlay"><i class="icon-spinner icon-spin icon-2x white"></i></div>');b.one("reloaded.ace.widget",function(){b.find(".widget-box-overlay").remove();t&&b.removeClass("position-relative")})}}else"settings"==c&&(f=a.Event("settings.ace.widget"),
b.trigger(f))})};ace.widget_reload_handler=function(a){a(document).on("reload.ace.widget",".widget-box",function(c){var e=a(this);setTimeout(function(){e.trigger("reloaded.ace.widget")},parseInt(1E3*Math.random()+1E3))})};
ace.enable_search_ahead=function(a){ace.variable_US_STATES="Alabama;Alaska;Arizona;Arkansas;California;Colorado;Connecticut;Delaware;Florida;Georgia;Hawaii;Idaho;Illinois;Indiana;Iowa;Kansas;Kentucky;Louisiana;Maine;Maryland;Massachusetts;Michigan;Minnesota;Mississippi;Missouri;Montana;Nebraska;Nevada;New Hampshire;New Jersey;New Mexico;New York;North Dakota;North Carolina;Ohio;Oklahoma;Oregon;Pennsylvania;Rhode Island;South Carolina;South Dakota;Tennessee;Texas;Utah;Vermont;Virginia;Washington;West Virginia;Wisconsin;Wyoming".split(";");try{a("#nav-search-input").typeahead({source:ace.variable_US_STATES,
updater:function(c){a("#nav-search-input").focus();return c}})}catch(c){}};
ace.switch_direction=function(a){function c(a,b){e.find("."+a).removeClass(a).addClass("tmp-rtl-"+a).end().find("."+b).removeClass(b).addClass(a).end().find(".tmp-rtl-"+a).removeClass("tmp-rtl-"+a).addClass(b)}var e=a(document.body);e.toggleClass("rtl").find(".dropdown-menu:not(.datepicker-dropdown,.colorpicker)").toggleClass("pull-right").end().find(".pull-right:not(.dropdown-menu,blockquote,.profile-skills .pull-right)").removeClass("pull-right").addClass("tmp-rtl-pull-right").end().find(".pull-left:not(.dropdown-submenu,.profile-skills .pull-left)").removeClass("pull-left").addClass("pull-right").end().find(".tmp-rtl-pull-right").removeClass("tmp-rtl-pull-right").addClass("pull-left").end().find(".chosen-container").toggleClass("chosen-rtl").end();c("align-left",
"align-right");c("no-padding-left","no-padding-right");c("arrowed","arrowed-right");c("arrowed-in","arrowed-in-right");c("messagebar-item-left","messagebar-item-right");var b=a("#piechart-placeholder");0<b.size()&&(a=a(document.body).hasClass("rtl")?"nw":"ne",b.data("draw").call(b.get(0),b,b.data("chart"),a))};$(window).load(function(){(function(){var a=$.fn.addClass;$.fn.addClass=function(){var c=a.apply(this,arguments);$(this).trigger("classAdded",arguments);return c}})();(function(){var a=$.fn.removeClass;$.fn.removeClass=function(){var c=a.apply(this,arguments);$(this).trigger("classRemoved",arguments);return c}})();setTimeout(function(){$(".scrollbar-hidden").jScrollPane({showArrows:!0,verticalArrowPositions:"split",horizontalArrowPositions:"split"})},0);$(function(){$(".scrollbar-hidden").bind("jsp-initialised",
function(a,c){$(this).find(".jspHorizontalBar, .jspVerticalBar").hide()}).jScrollPane().hover(function(){$(this).find(".jspHorizontalBar, .jspVerticalBar").stop().fadeTo("fast",0.9)},function(){$(this).find(".jspHorizontalBar, .jspVerticalBar").stop().fadeTo("fast",0)})})});
$.fn.textResize=function(a){!0!=$(this).data("textResize")&&($(this).data("textResize",!0),$(this).data("textResizeOriginalText",$(this).text().trim()));var c=Math.floor(a.containerWidth/a.charPxlWidth),e=a.text?a.text:$(this).text().trim(),b=Math.floor(a.desiredHeight/a.fontSize),b=a.trailingDots?Math.floor(c*b)-3:Math.floor(c*b);Math.floor(a.fontSize*Math.floor(e.length/c))>a.desiredHeight?(a=e.split("").splice(0,b).join("")+(a.trailingDots?"...":""),$(this).html(a)):a.text&&$(this).html(e);return this};$(window).load(function(){$(".result").on("click",function(){var a=$(this);a.hasClass("active-single")?a.removeClass("active-single"):($.each($(".result"),function(a,c){$(c).removeClass("active-single")}),a.addClass("active-single"))});$(".checkmark").on("click",function(a){a.preventDefault(!0);a.stopPropagation();a=$(this).parents(".result");a.hasClass("active-multi")?a.removeClass("active-multi"):a.addClass("active-multi")});$(".filter").on("click",function(){var a=$(this);a.hasClass("active")?
a.removeClass("active"):a.addClass("active")});$(".msglist .toggle").on("click",function(){$(".msglist").toggleClass("docked")});var a=function(){};a.prototype={resizeMsgBody:function(){var a=$(".msgview_bottom").offset().top-$(".msgview_middle").offset().top;$(".msgview_middle").css("height",a);return $(".msgview_middle")}};var c=new a;$(".msgview_bottom .expandable-toggle").on("click",function(){$(this).parents(".msgview_bottom").toggleClass("attachments-hidden");setTimeout(function(){c.resizeMsgBody().data("jsp").reinitialise();
$(".scrollbar-hidden").data("jsp").reinitialise()},300)});$(window).on("resize",function(){c.resizeMsgBody().data("jsp").reinitialise();$(".scrollbar-hidden").data("jsp").reinitialise()});setTimeout(function(){c.resizeMsgBody()},0);$(".result").on("classAdded",function(a,b){if("collapsed"===b){var c=$(this).find(".widget-main");$(this).find(".widget-main").textResize({charPxlWidth:7,fontSize:11,desiredHeight:11,trailingDots:!0,containerWidth:c.width()})}});$(".result").on("classRemoved",function(a,
b){if("collapsed"===b){var c=$(this).find(".widget-main"),f=$(this).find(".widget-box");c.textResize({text:c.data("textResizeOriginalText"),charPxlWidth:7,fontSize:11,desiredHeight:44,containerWidth:f.width()})}});$(".msglist").on("toggleDock",function(){!1===$(this).toggleClass("docked").hasClass("docked")&&$(".message-list-container").css("left","237px")});$.each($(".result"),function(a,b){var c=$(this).find(".widget-main"),f=$(this).find(".widget-box");c.textResize({charPxlWidth:7,fontSize:11,
desiredHeight:44,containerWidth:f.width()})});$(".main").splitter({type:"v",outline:!0,minLeft:530,minRight:310,resizeToWidth:!0,cookie:"docksplitter",accessKey:"I"})});