//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 07:22:02 PM EDT 
//


package com.reqo.ironhold.reader.bloomberg.model.msg;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}FileName"/>
 *           &lt;element ref="{}Reference"/>
 *         &lt;/choice>
 *         &lt;element ref="{}FileID" minOccurs="0"/>
 *         &lt;element ref="{}FileSize" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "fileName",
        "reference",
        "fileID",
        "fileSize"
})
@XmlRootElement(name = "Attachment")
public class Attachment {

    @XmlElement(name = "FileName")
    protected FileName fileName;
    @XmlElement(name = "Reference")
    protected Reference reference;
    @XmlElement(name = "FileID")
    protected FileID fileID;
    @XmlElement(name = "FileSize")
    protected FileSize fileSize;

    /**
     * Gets the value of the fileName property.
     *
     * @return possible object is
     *         {@link FileName }
     */
    public FileName getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     *
     * @param value allowed object is
     *              {@link FileName }
     */
    public void setFileName(FileName value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the reference property.
     *
     * @return possible object is
     *         {@link Reference }
     */
    public Reference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     *
     * @param value allowed object is
     *              {@link Reference }
     */
    public void setReference(Reference value) {
        this.reference = value;
    }

    /**
     * Gets the value of the fileID property.
     *
     * @return possible object is
     *         {@link FileID }
     */
    public FileID getFileID() {
        return fileID;
    }

    /**
     * Sets the value of the fileID property.
     *
     * @param value allowed object is
     *              {@link FileID }
     */
    public void setFileID(FileID value) {
        this.fileID = value;
    }

    /**
     * Gets the value of the fileSize property.
     *
     * @return possible object is
     *         {@link FileSize }
     */
    public FileSize getFileSize() {
        return fileSize;
    }

    /**
     * Sets the value of the fileSize property.
     *
     * @param value allowed object is
     *              {@link FileSize }
     */
    public void setFileSize(FileSize value) {
        this.fileSize = value;
    }

}
