//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 07:22:02 PM EDT 
//


package com.reqo.ironhold.reader.bloomberg.model.msg;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MsgID"/>
 *         &lt;element ref="{}MsgTime"/>
 *         &lt;element ref="{}MsgTimeUTC"/>
 *         &lt;element ref="{}MsgLang"/>
 *         &lt;element ref="{}MsgType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}OnBehalfOf"/>
 *           &lt;element ref="{}SharedMessenger"/>
 *         &lt;/choice>
 *         &lt;element ref="{}OrigSender" minOccurs="0"/>
 *         &lt;element ref="{}Sender"/>
 *         &lt;element ref="{}Recipient" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Subject"/>
 *         &lt;element ref="{}Attachment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}MsgBody"/>
 *         &lt;element ref="{}DisclaimerReference" minOccurs="0"/>
 *         &lt;element ref="{}Greeting" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "msgID",
        "msgTime",
        "msgTimeUTC",
        "msgLang",
        "msgType",
        "onBehalfOf",
        "sharedMessenger",
        "origSender",
        "sender",
        "recipient",
        "subject",
        "attachment",
        "msgBody",
        "disclaimerReference",
        "greeting"
})
@XmlRootElement(name = "Message")
public class Message {

    @XmlElement(name = "MsgID", required = true)
    protected MsgID msgID;
    @XmlElement(name = "MsgTime", required = true)
    protected MsgTime msgTime;
    @XmlElement(name = "MsgTimeUTC", required = true)
    protected MsgTimeUTC msgTimeUTC;
    @XmlElement(name = "MsgLang", required = true)
    protected MsgLang msgLang;
    @XmlElement(name = "MsgType")
    protected MsgType msgType;
    @XmlElement(name = "OnBehalfOf")
    protected OnBehalfOf onBehalfOf;
    @XmlElement(name = "SharedMessenger")
    protected SharedMessenger sharedMessenger;
    @XmlElement(name = "OrigSender")
    protected OrigSender origSender;
    @XmlElement(name = "Sender", required = true)
    protected Sender sender;
    @XmlElement(name = "Recipient", required = true)
    protected List<Recipient> recipient;
    @XmlElement(name = "Subject", required = true)
    protected Subject subject;
    @XmlElement(name = "Attachment")
    protected List<Attachment> attachment;
    @XmlElement(name = "MsgBody", required = true)
    protected MsgBody msgBody;
    @XmlElement(name = "DisclaimerReference")
    protected DisclaimerReference disclaimerReference;
    @XmlElement(name = "Greeting")
    protected Greeting greeting;

    /**
     * Gets the value of the msgID property.
     *
     * @return possible object is
     *         {@link MsgID }
     */
    public MsgID getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     *
     * @param value allowed object is
     *              {@link MsgID }
     */
    public void setMsgID(MsgID value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the msgTime property.
     *
     * @return possible object is
     *         {@link MsgTime }
     */
    public MsgTime getMsgTime() {
        return msgTime;
    }

    /**
     * Sets the value of the msgTime property.
     *
     * @param value allowed object is
     *              {@link MsgTime }
     */
    public void setMsgTime(MsgTime value) {
        this.msgTime = value;
    }

    /**
     * Gets the value of the msgTimeUTC property.
     *
     * @return possible object is
     *         {@link MsgTimeUTC }
     */
    public MsgTimeUTC getMsgTimeUTC() {
        return msgTimeUTC;
    }

    /**
     * Sets the value of the msgTimeUTC property.
     *
     * @param value allowed object is
     *              {@link MsgTimeUTC }
     */
    public void setMsgTimeUTC(MsgTimeUTC value) {
        this.msgTimeUTC = value;
    }

    /**
     * Gets the value of the msgLang property.
     *
     * @return possible object is
     *         {@link MsgLang }
     */
    public MsgLang getMsgLang() {
        return msgLang;
    }

    /**
     * Sets the value of the msgLang property.
     *
     * @param value allowed object is
     *              {@link MsgLang }
     */
    public void setMsgLang(MsgLang value) {
        this.msgLang = value;
    }

    /**
     * Gets the value of the msgType property.
     *
     * @return possible object is
     *         {@link MsgType }
     */
    public MsgType getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     *
     * @param value allowed object is
     *              {@link MsgType }
     */
    public void setMsgType(MsgType value) {
        this.msgType = value;
    }

    /**
     * Gets the value of the onBehalfOf property.
     *
     * @return possible object is
     *         {@link OnBehalfOf }
     */
    public OnBehalfOf getOnBehalfOf() {
        return onBehalfOf;
    }

    /**
     * Sets the value of the onBehalfOf property.
     *
     * @param value allowed object is
     *              {@link OnBehalfOf }
     */
    public void setOnBehalfOf(OnBehalfOf value) {
        this.onBehalfOf = value;
    }

    /**
     * Gets the value of the sharedMessenger property.
     *
     * @return possible object is
     *         {@link SharedMessenger }
     */
    public SharedMessenger getSharedMessenger() {
        return sharedMessenger;
    }

    /**
     * Sets the value of the sharedMessenger property.
     *
     * @param value allowed object is
     *              {@link SharedMessenger }
     */
    public void setSharedMessenger(SharedMessenger value) {
        this.sharedMessenger = value;
    }

    /**
     * Gets the value of the origSender property.
     *
     * @return possible object is
     *         {@link OrigSender }
     */
    public OrigSender getOrigSender() {
        return origSender;
    }

    /**
     * Sets the value of the origSender property.
     *
     * @param value allowed object is
     *              {@link OrigSender }
     */
    public void setOrigSender(OrigSender value) {
        this.origSender = value;
    }

    /**
     * Gets the value of the sender property.
     *
     * @return possible object is
     *         {@link Sender }
     */
    public Sender getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     *
     * @param value allowed object is
     *              {@link Sender }
     */
    public void setSender(Sender value) {
        this.sender = value;
    }

    /**
     * Gets the value of the recipient property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recipient property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecipient().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Recipient }
     */
    public List<Recipient> getRecipient() {
        if (recipient == null) {
            recipient = new ArrayList<Recipient>();
        }
        return this.recipient;
    }

    /**
     * Gets the value of the subject property.
     *
     * @return possible object is
     *         {@link Subject }
     */
    public Subject getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     *
     * @param value allowed object is
     *              {@link Subject }
     */
    public void setSubject(Subject value) {
        this.subject = value;
    }

    /**
     * Gets the value of the attachment property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachment property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachment().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Attachment }
     */
    public List<Attachment> getAttachment() {
        if (attachment == null) {
            attachment = new ArrayList<Attachment>();
        }
        return this.attachment;
    }

    /**
     * Gets the value of the msgBody property.
     *
     * @return possible object is
     *         {@link MsgBody }
     */
    public MsgBody getMsgBody() {
        return msgBody;
    }

    /**
     * Sets the value of the msgBody property.
     *
     * @param value allowed object is
     *              {@link MsgBody }
     */
    public void setMsgBody(MsgBody value) {
        this.msgBody = value;
    }

    /**
     * Gets the value of the disclaimerReference property.
     *
     * @return possible object is
     *         {@link DisclaimerReference }
     */
    public DisclaimerReference getDisclaimerReference() {
        return disclaimerReference;
    }

    /**
     * Sets the value of the disclaimerReference property.
     *
     * @param value allowed object is
     *              {@link DisclaimerReference }
     */
    public void setDisclaimerReference(DisclaimerReference value) {
        this.disclaimerReference = value;
    }

    /**
     * Gets the value of the greeting property.
     *
     * @return possible object is
     *         {@link Greeting }
     */
    public Greeting getGreeting() {
        return greeting;
    }

    /**
     * Sets the value of the greeting property.
     *
     * @param value allowed object is
     *              {@link Greeting }
     */
    public void setGreeting(Greeting value) {
        this.greeting = value;
    }

}
