//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 07:22:02 PM EDT 
//


package com.reqo.ironhold.reader.bloomberg.model.msg;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.reqo.ironhold.reader.bloomberg.model.msg package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.reqo.ironhold.reader.bloomberg.model.msg
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Attachment }
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link FileName }
     */
    public FileName createFileName() {
        return new FileName();
    }

    /**
     * Create an instance of {@link Reference }
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link FileID }
     */
    public FileID createFileID() {
        return new FileID();
    }

    /**
     * Create an instance of {@link FileSize }
     */
    public FileSize createFileSize() {
        return new FileSize();
    }

    /**
     * Create an instance of {@link CorporateEmailAddress }
     */
    public CorporateEmailAddress createCorporateEmailAddress() {
        return new CorporateEmailAddress();
    }

    /**
     * Create an instance of {@link DisclaimerReference }
     */
    public DisclaimerReference createDisclaimerReference() {
        return new DisclaimerReference();
    }

    /**
     * Create an instance of {@link OnBehalfOf }
     */
    public OnBehalfOf createOnBehalfOf() {
        return new OnBehalfOf();
    }

    /**
     * Create an instance of {@link UserInfo }
     */
    public UserInfo createUserInfo() {
        return new UserInfo();
    }

    /**
     * Create an instance of {@link FirstName }
     */
    public FirstName createFirstName() {
        return new FirstName();
    }

    /**
     * Create an instance of {@link LastName }
     */
    public LastName createLastName() {
        return new LastName();
    }

    /**
     * Create an instance of {@link FirmNumber }
     */
    public FirmNumber createFirmNumber() {
        return new FirmNumber();
    }

    /**
     * Create an instance of {@link AccountName }
     */
    public AccountName createAccountName() {
        return new AccountName();
    }

    /**
     * Create an instance of {@link AccountNumber }
     */
    public AccountNumber createAccountNumber() {
        return new AccountNumber();
    }

    /**
     * Create an instance of {@link BloombergUUID }
     */
    public BloombergUUID createBloombergUUID() {
        return new BloombergUUID();
    }

    /**
     * Create an instance of {@link BloombergEmailAddress }
     */
    public BloombergEmailAddress createBloombergEmailAddress() {
        return new BloombergEmailAddress();
    }

    /**
     * Create an instance of {@link ClientID1 }
     */
    public ClientID1 createClientID1() {
        return new ClientID1();
    }

    /**
     * Create an instance of {@link ClientID2 }
     */
    public ClientID2 createClientID2() {
        return new ClientID2();
    }

    /**
     * Create an instance of {@link MsgTime }
     */
    public MsgTime createMsgTime() {
        return new MsgTime();
    }

    /**
     * Create an instance of {@link OrigSender }
     */
    public OrigSender createOrigSender() {
        return new OrigSender();
    }

    /**
     * Create an instance of {@link NextFile }
     */
    public NextFile createNextFile() {
        return new NextFile();
    }

    /**
     * Create an instance of {@link MsgTimeUTC }
     */
    public MsgTimeUTC createMsgTimeUTC() {
        return new MsgTimeUTC();
    }

    /**
     * Create an instance of {@link MsgType }
     */
    public MsgType createMsgType() {
        return new MsgType();
    }

    /**
     * Create an instance of {@link Greeting }
     */
    public Greeting createGreeting() {
        return new Greeting();
    }

    /**
     * Create an instance of {@link Sender }
     */
    public Sender createSender() {
        return new Sender();
    }

    /**
     * Create an instance of {@link MsgBody }
     */
    public MsgBody createMsgBody() {
        return new MsgBody();
    }

    /**
     * Create an instance of {@link Version }
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link Recipient }
     */
    public Recipient createRecipient() {
        return new Recipient();
    }

    /**
     * Create an instance of {@link ForwardedBy }
     */
    public ForwardedBy createForwardedBy() {
        return new ForwardedBy();
    }

    /**
     * Create an instance of {@link ForwardedTo }
     */
    public ForwardedTo createForwardedTo() {
        return new ForwardedTo();
    }

    /**
     * Create an instance of {@link Subject }
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link MsgLang }
     */
    public MsgLang createMsgLang() {
        return new MsgLang();
    }

    /**
     * Create an instance of {@link Message }
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link MsgID }
     */
    public MsgID createMsgID() {
        return new MsgID();
    }

    /**
     * Create an instance of {@link SharedMessenger }
     */
    public SharedMessenger createSharedMessenger() {
        return new SharedMessenger();
    }

    /**
     * Create an instance of {@link FileDump }
     */
    public FileDump createFileDump() {
        return new FileDump();
    }

    /**
     * Create an instance of {@link Disclaimer }
     */
    public Disclaimer createDisclaimer() {
        return new Disclaimer();
    }

    /**
     * Create an instance of {@link DisclaimerText }
     */
    public DisclaimerText createDisclaimerText() {
        return new DisclaimerText();
    }

}
